bash loo_AC.sh &
bash loo_b.sh &
bash loo_BP.sh &
bash loo_BSU.sh &
bash loo_BTH_.sh &
bash loo_BT_.sh &
bash loo_CCNA_.sh &
bash loo_Cj.sh &
bash loo_FT.sh &
bash loo_HI.sh &
bash loo_HP.sh &
bash loo_MG_.sh &
bash loo_MY.sh &
bash loo_PA14_.sh &
bash loo_PA.sh &
bash loo_PGN_.sh &
bash loo_Rv.sh &
bash loo_SA.sh &
bash loo_SAOU.sh &
bash loo_SO.sh &
bash loo_spr.sh &
bash loo_Spy.sh &
bash loo_SSA_.sh &
bash loo_STM.sh &
bash loo_Swit_.sh &
bash loo_t.sh &
bash loo_VC.sh &
